# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
  pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git', branch: 'master'
  pod 'IRCameraSticker', :path => '../IRCameraSticker.podspec'
end
